{
 "title": "Starlet FSLIB / Workloads (Standard)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "GROUP",
    "label": "NodeGroup",
    "query": {
     "query": "label_values(fslib_fs_open_files, job)"
    }
   },
   {
    "name": "filesystem",
    "label": "Filesystem",
    "query": {
     "query": "label_values(fslib_fs_open_files{job=\"$GROUP\"}, fstype)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(fslib_fs_open_files{job=\"$GROUP\"}, instance)"
    }
   },
   { "name": "quantile", "query": "0.5,0.9,0.95,0.99,0.999" }
  ]
 },
 "panels": [
  {
   "title": "FSLIB READ IO METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "fslib read io_latency (quantile)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(fslib_read_io_latency_bucket{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]))",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib read io_latency (average)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(fslib_read_io_latency_sum{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]) / rate(fslib_read_io_latency_count{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib total read data",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "fslib_read_io_size_sum{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib read iosize (quantile)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(fslib_read_io_size_bucket{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]))",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib read iosize (average)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(fslib_read_io_size_sum{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]) / rate(fslib_read_io_size_count{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib read throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(fslib_read_io_size_sum{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib read iops",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(fslib_read_io_size_count{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "FSLIB WRITE IO METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "fslib write io_latency (quantile)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(fslib_write_io_latency_bucket{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]))",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib write io_latency (average)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(fslib_write_io_latency_sum{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]) / rate(fslib_write_io_latency_count{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib total write data",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "fslib_write_io_size_sum{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib write iosize (quantile)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(fslib_write_io_size_bucket{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]))",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib write iosize (average)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(fslib_write_io_size_sum{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]) / rate(fslib_write_io_size_count{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib write throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(fslib_write_io_size_sum{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib write iops",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(fslib_write_io_size_count{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib close latency (quantile)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(fslib_close_io_latency_bucket{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]))",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "S3 IO METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "fslib s3 single upload iops",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(fslib_s3_single_upload_size_count{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
       "legendFormat": "{{fstype}}_{{instance}}"
      }
     ]
    },
    {
     "title": "fslib s3 single upload iosize (quantile)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(fslib_s3_single_upload_size_bucket{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]))",
       "legendFormat": "{{fstype}}_{{instance}}"
      }
     ]
    },
    {
     "title": "fslib s3 single upload latency (quantile)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(fslib_s3_single_upload_latency_bucket{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]))",
       "legendFormat": "{{fstype}}_{{instance}}"
      }
     ]
    },
    {
     "title": "fslib s3 multi upload iops",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(fslib_s3_multi_upload_size_count{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
       "legendFormat": "{{fstype}}_{{instance}}"
      }
     ]
    },
    {
     "title": "fslib s3 multi upload iosize (quantile)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(fslib_s3_multi_upload_size_bucket{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]))",
       "legendFormat": "{{fstype}}_{{instance}}"
      }
     ]
    },
    {
     "title": "fslib s3 multi upload latency (quantile)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(fslib_s3_multi_upload_latency_bucket{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]))",
       "legendFormat": "{{fstype}}_{{instance}}"
      }
     ]
    },
    {
     "title": "fslib s3 complete multi upload latency (quantile)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(fslib_s3_complete_multi_upload_latency_bucket{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]))",
       "legendFormat": "{{fstype}}_{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FSLIB CACHE METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {}
   ]
  },
  {
   "title": "fslib cache eviction (TOTAL)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fslib_cache_ttl_evictions{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(fslib_open_cache_hits{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]) / (rate(fslib_open_cache_hits{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]) + rate(fslib_open_cache_misses{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]))",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib cache hits/misses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(fslib_open_cache_hits{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "cachehits_{{fstype}}_{{instance}}"
    },
    {
     "expr": "rate(fslib_open_cache_misses{fstype=~\"$filesystem\", instance=\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "cachemiss_{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib star cache meta memory size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "fslib_star_cache_meta_memory_size{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib star cache data disk size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "fslib_star_cache_disk_size{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib star cache data memory size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "fslib_star_cache_memory_size{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "FSLIB FS METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {}
   ]
  },
  {
   "title": "fslib alive fs instances count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fslib_fs_instance_count{instance=~\"$instance\", job=\"$GROUP\"}",
     "legendFormat": "fslib_fs_instance"
    }
   ]
  },
  {
   "title": "fslib open files",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fslib_fs_open_files{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib create files",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(fslib_fs_create_files{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "create_{{fstype}}_{{instance}}"
    },
    {
     "expr": "rate(fslib_open_cache_misses{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "cachemiss_create_{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "filesystem meta operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(fslib_list_dir{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "listdir_{{fstype}}_{{instance}}"
    },
    {
     "expr": "rate(fslib_entry_exists{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "entry_exists_{{fstype}}_{{instance}}"
    },
    {
     "expr": "rate(fslib_entry_stat{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "entry_stat_{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib async caches",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fslib_async_cache_files{instance=~\"$instance\", job=\"$GROUP\"}",
     "legendFormat": "async_cache_{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib create files (TOTAL)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fslib_fs_create_files{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}",
     "legendFormat": "createfiles_{{fstype}}_{{instance}}"
    },
    {
     "expr": "fslib_open_cache_misses{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}",
     "legendFormat": "cachemiss_create_{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib async tasks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fslib_cache_async_tasks{instance=~\"$instance\", job=\"$GROUP\"}",
     "legendFormat": "async_tasks/{{task_type}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib async writeback",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fslib_cache_async_writes{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}",
     "legendFormat": "async_writes_{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib list latency (quantile)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(fslib_list_latency_bucket{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]))",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib list latency (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(fslib_list_latency_sum{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]) / rate(fslib_list_latency_count{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "FSLIB DELETE IO METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 },
   "targets": [
    {}
   ]
  },
  {
   "title": "fslib delete files io latency (quantile)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(fslib_delete_files_io_latency_bucket{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]))",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib delete files io latency (average)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(fslib_delete_files_io_latency_sum{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]) / rate(fslib_delete_files_io_latency_count{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib delete file io latency (quantile)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(fslib_delete_file_io_latency_bucket{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]))",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib delete file io latency (average)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(fslib_delete_file_io_latency_sum{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]) / rate(fslib_delete_file_io_latency_count{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib delete dir io latency (quantile)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(fslib_delete_dir_io_latency_bucket{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]))",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  },
  {
   "title": "fslib delete dir io latency (average)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(fslib_delete_dir_io_latency_sum{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval]) / rate(fslib_delete_dir_io_latency_count{fstype=~\"$filesystem\", instance=~\"$instance\", job=\"$GROUP\"}[$__rate_interval])",
     "legendFormat": "{{fstype}}_{{instance}}"
    }
   ]
  }
 ]
}